version: '2'

services:

  notifications:
    container_name: notifications
    build:
      context: .
      dockerfile: './dockerize/Dockerfile'
    command: npm run start:debug
    expose:
      - 3000
    ports: 
      - 5555:5555
    volumes:
     - .:/usr/src/app

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./etc/nginx/conf.d/default.conf.nginx:/etc/nginx/conf.d/default.conf
    depends_on:
      - notifications
